# Generated by Django 2.1.2 on 2018-11-29 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0002_auto_20181130_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupa',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='groupa',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouping', to=settings.AUTH_USER_MODEL),
        ),
    ]
