# Generated by Django 2.1.2 on 2018-11-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_auto_20181130_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupa',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='groupa',
            name='location',
        ),
    ]
