# Generated by Django 2.1.2 on 2018-11-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kilogram', '0005_auto_20181130_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupa',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='groupb',
            name='user_b',
        ),
        migrations.DeleteModel(
            name='GroupA',
        ),
        migrations.DeleteModel(
            name='GroupB',
        ),
    ]
